version: "3"

services:
  app:
    environment:
      - DATABASE_URL=file:./prod.db
    build: .
    command: npm run start:prod
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/src/
      - nodemodules:/src/node_modules

volumes:
  nodemodules: {}