apiVersion: v1
kind: Service
metadata:
  name: metrics-service
spec:
  selector:
    app: foodbairro
  ports:
    - name: metrics-port
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodbairro
  template:
    metadata:
      labels:
        app: foodbairro
    spec:
      containers:
        - name: metrics-container
          image: davijr/foodbairro:latest
          ports:
            - containerPort: 80
